### ISSUE TITLE
Get Dagster-sqlmesh running on Trino

### ISSUE THREAD

**Issue by ryscheng** [opensource-observer/oso#2296] opened 2024-10-02 21:45 UTC
### What is it?

We are currrently running Trino manually on k8s.

We should setup our sqlmesh on Dagster setup to be able to execute jobs/runs on this new cluster

**Comment by ravenac95** [comment] 2024-12-03 17:30
Duplicate of #2474. I'll take that one instead.

**Closed by ravenac95** 2024-12-03 17:30 UTC
